name: Build WeatherDisplay on PR

on:
  pull_request:
    branches:
      - '**'  # This will trigger for PRs to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libwiringpi-dev libcurl4-openssl-dev

      # Install nlohmann/json
      - name: Install nlohmann/json
        run: |
          mkdir -p /tmp/json
          curl -L https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp -o /tmp/json/json.hpp

      - name: Verify nlohmann/json file download
        run: |
          ls -l /tmp/json/json.hpp
          cat /tmp/json/json.hpp | head -n 20  # Display the first 20 lines to confirm content

      - name: Build WeatherDisplay
        run: |
          set -e
          g++ -o weather main.cpp weather.cpp lcd.cpp -lwiringPi -lcurl -I/tmp/json
          echo "Build completed successfully."

      - name: List built files
        run: ls -l weather
