name: Build WeatherDisplay on PR

on:
  pull_request:
    branches:
      - '**'  # Trigger for PRs to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Inject your API key from repository secrets (set in GitHub Settings > Secrets > Actions)
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      WEATHER_LOCATION: ${{ vars.WEATHER_LOCATION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libwiringpi-dev libcurl4-openssl-dev

      - name: Build WeatherDisplay
        run: |
          set -e
          echo "[INFO] Building WeatherDisplay..."
          g++ -o weather main.cpp weather.cpp lcd.cpp -lwiringPi -lcurl -I./include -std=c++11

      - name: Verify environment variable (masked)
        run: |
          if [ -z "$WEATHER_API_KEY" ]; then
            echo "::error::WEATHER_API_KEY is not set. Please configure it in repo settings."
            exit 1
          else
            echo "[INFO] WEATHER_API_KEY detected (value is masked in logs)."
          fi

      - name: List built files
        run: ls -l weather
