name: Build WeatherDisplay on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential g++ libwiringpi-dev

      - name: Build WeatherDisplay
        run: |
          set -e
          g++ -o weather main.cpp weather.cpp lcd.cpp -lwiringPi
          echo "Build completed successfully."

      - name: List built files
        run: ls -l weather
